name: scrape_wow_ah

on: 
  schedule:
    - cron: '7 * * * *' # Run every 5 minutes
  
jobs:
  build:
    runs-on: ubuntu-latest # THink set OS here
    steps:
    
      - name: checkout repo content
        uses: actions/checkout@v2

      - name: create-json
        id: create-json
        uses: jsdaniell/create-json@1.1.2
        with:
          name: "credentials.json"
          json: ${{secrets.GDRIVE_CREDENTIALS}}
        
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install pandas==1.3.5 requests==2.26.0 dropbox==10.9.0
          
      - name: execute py script # run scrape_AH.py to get the latest data
        env: 
          CLIENT_ID_WOW: ${{ secrets.CLIENT_ID_WOW }}
          CLIENT_SECRET_WOW: ${{ secrets.CLIENT_SECRET_WOW }}
          DROPBOX_ACCESS: ${{ secrets.DROPBOX_ACCESS}}
        run: python scrape_AH.py
