name: scrape_wow_ah

on: push
  #schedule:
  #  - cron: '0 * * * *' # Run every hour, I think?
  
jobs:
  build:
    runs-on: ubuntu-latest # THink set OS here
    steps:
    
      - name: checkout repo content
        uses: actions/checkout@v2
        
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install pandas==1.3.5 requests==2.26.0 pydrive==1.3.1
          
      - name: execute py script # run scrape_AH.py to get the latest data
        env: 
          CLIENT_ID_WOW: ${{ secrets.CLIENT_ID_WOW }}
          CLIENT_SECRET_WOW: ${{ secrets.CLIENT_SECRET_WOW }}
        run: python scrape_AH.py
